### ISSUE TITLE
Does not work on OS X / node 5.10 / npm 3.8.3

### ISSUE THREAD

**Issue by MilovanovM** [developit/dropfox#2]
After `npm start` I'm getting:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.8.3
3 info using node@v5.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle dropfox@1.0.0~prestart: dropfox@1.0.0
6 silly lifecycle dropfox@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle dropfox@1.0.0~start: dropfox@1.0.0
8 verbose lifecycle dropfox@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle dropfox@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/maxmilovanov/projects/demoes/dropfox/node_modules/.bin:/usr/local/bin:/usr/local/lib/dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-rc1-final/bin:/Users/maxmilovanov/.dnx/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet/bin:/usr/local/git/bin:/usr/local/go/bin:/Users/maxmilovanov/go/bin
10 verbose lifecycle dropfox@1.0.0~start: CWD: /Users/maxmilovanov/projects/demoes/dropfox
11 silly lifecycle dropfox@1.0.0~start: Args: [ '-c',
11 silly lifecycle   'ENV=dev parallelshell \'npm run dev\' \'npm run thenelectron\'' ]
12 silly lifecycle dropfox@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle dropfox@1.0.0~start: Failed to exec start script
14 verbose stack Error: dropfox@1.0.0 start: `ENV=dev parallelshell 'npm run dev' 'npm run thenelectron'`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid dropfox@1.0.0
16 verbose cwd /Users/maxmilovanov/projects/demoes/dropfox
17 error Darwin 15.4.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.10.0
20 error npm  v3.8.3
21 error code ELIFECYCLE
22 error dropfox@1.0.0 start: `ENV=dev parallelshell 'npm run dev' 'npm run thenelectron'`
22 error Exit status 1
23 error Failed at the dropfox@1.0.0 start script 'ENV=dev parallelshell 'npm run dev' 'npm run thenelectron''.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the dropfox package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ENV=dev parallelshell 'npm run dev' 'npm run thenelectron'
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs dropfox
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls dropfox
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by developit** [comment]
Thanks for the report, I'm going to update the rather outdated dependencies and see if that helps.

**Comment by developit** [comment]
@MilovanovM I just updated 100% of the dependencies (they were very out of date). This should fix the error you encountered. Let me know!

**Comment by MilovanovM** [comment]
Still does not work

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.8.3
3 info using node@v5.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle dropfox@1.1.0~prestart: dropfox@1.1.0
6 silly lifecycle dropfox@1.1.0~prestart: no script for prestart, continuing
7 info lifecycle dropfox@1.1.0~start: dropfox@1.1.0
8 verbose lifecycle dropfox@1.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle dropfox@1.1.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/maxmilovanov/projects/demoes/dropfox/node_modules/.bin:/usr/local/bin:/usr/local/lib/dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-rc1-final/bin:/Users/maxmilovanov/.dnx/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet/bin:/usr/local/git/bin:/usr/local/go/bin:/Users/maxmilovanov/go/bin
10 verbose lifecycle dropfox@1.1.0~start: CWD: /Users/maxmilovanov/projects/demoes/dropfox
11 silly lifecycle dropfox@1.1.0~start: Args: [ '-c',
11 silly lifecycle   'ENV=development npm-run-all build:assets build:transpilewrap --parallel dev thenelectron' ]
12 info lifecycle dropfox@1.1.0~start: Failed to exec start script
13 verbose stack Error: dropfox@1.1.0 start: `ENV=development npm-run-all build:assets build:transpilewrap --parallel dev thenelectron`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:100:13)
13 verbose stack     at ChildProcess.emit (events.js:185:7)
13 verbose stack     at maybeClose (internal/child_process.js:850:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
14 verbose pkgid dropfox@1.1.0
15 verbose cwd /Users/maxmilovanov/projects/demoes/dropfox
16 error Darwin 15.4.0
17 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 error node v5.10.0
19 error npm  v3.8.3
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error dropfox@1.1.0 start: `ENV=development npm-run-all build:assets build:transpilewrap --parallel dev thenelectron`
24 error spawn ENOENT
25 error Failed at the dropfox@1.1.0 start script 'ENV=development npm-run-all build:assets build:transpilewrap --parallel dev thenelectron'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the dropfox package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     ENV=development npm-run-all build:assets build:transpilewrap --parallel dev thenelectron
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs dropfox
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls dropfox
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
```
